### ISSUE TITLE
sync my local directory sources to an existing component

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#207]
I want to be able to code locally and have it sync my changes to my running component and be smart enough to let me know when a restart of the container is required if dependencies have changed. This should work across PHP, Node.JS, Python, Ruby, and Java.

```
$ cd myfrontend
$ ocd create php:5.4
$ ocd push
$ ocd watch [.]  //blocks terminal and watches for file changes

Output:
Watching for changes.  To stop, use control-c
[11:34:12] myfile.php was pushed
[12:04:05] logo.png was pushed
```

Subtask of #160 

There's work in progress to demonstrate how this could work done by @grahamdumpleton and @jorgemoralespou

**Comment by kadel** [comment]
Just to make sure that I understand that correctly.

The build process should be slightly different than regular s2i using BuildConfig.
Application container will be constantly running. 
`ocdev watch` will be continuously watching local source directory and when there is a change in the source it will sync it to the running container. Whan this happens something should trigger reload or restart (but it won't restart container, only the process running given program).


This will mean that we will have to use a special image for this as it will require runtime and also build dependencies.
Before this application will be deployed to production it will require another "clean" build (without build dependencies). This will complicate propagation to production process  :-(

Would it be better to use normal s2i with BuildConfig? If we have good s2i images with support for incremental builds whole rebuild process will be quick. From the beginning, the application will be running in a clean image that will be also used for production deployment.

**Comment by slemeur** [comment]
I would move forward with the normal s2i, which would allow to deliver the user story in a short time.

Once we'll have an initial release we will have time to refine this and use different components.

**Comment by jorgemoralespou** [comment]
@kadel @slemeur yes, we should move forward as this really would require some changes/tweaks to the DeploymentConfig. Ideally (when solved) we will modify the DeploymentConfig to have a supervisor process, that will be injected via an Init container, that will take care of properly reloading the server when appropriate. As mentioned in the initial issue, there's a prototype working, and we would probably sync. The one that's done most of the work and has most of the knowledge from our side is @GrahamDumpleton. He's in Sydney TZ, so we can sync early in the morning any day.

I would defer this for now, or create a follow up task.

**Comment by jorgemoralespou** [comment]
We should not consider watch for scaled workloads of more than 1 pod

**Comment by kadel** [comment]
First steps towards this are done in #325 - right now it just sync files the same way `oc rsync` does. The only difference is that it automatically detects pod for component and target path in pod is hardcoded to `/opt/app-root/src/`

**Comment by kadel** [comment]
Some notes from Jorge:

When you create a component, by default should create the deployment config with the init-container and Graham's hack that will copy the s2i assemble scripts to the image and install/create the supervisor process.

When you update the component to use git it should remove this configuration.

When you update this component to either local/binary it should add back this configuration.

"odo push" should just upload the files, and then the supervisor will trigger the "internal" build and reload of the process.

Similarly "odo watch" should do the same but on a watch mode, instead of one time "sync call".

I think most of this is already configured in Graham's example. [1] 
One thing that we could potentially do is prepare different supervisor configuration based on the images being run, so that it injects the appropriate reload logic for every image in case the original "run" script is not enough [2]



[1] https://github.com/openshift-evangelists/pseudo-vps-quickstart
[2] https://github.com/openshift-evangelists/pseudo-vps-quickstart#running-an-application-permanently

**Comment by LalatenduMohanty** [comment]
Moved the comment to https://github.com/redhat-developer/odo/pull/408#issuecomment-387500552
