### ISSUE TITLE
Ability to create additional resources

### ISSUE THREAD

**Issue by deweya** [redhat-developer/odo#2142]
[kind/Feature]

## Which functionality do you think we should add?
odo should allow a developer to create additional configmaps, secrets, custom resources, etc alongside a deployment.

Additionally, odo should allow a developer to specify mounts in cases where they want to create configmaps and secrets for config purposes.

## Why is this needed?
I imagine there will be use cases where a developer wants to deploy configmaps, secrets, and potentially custom resources alongside a deployment for configuration. The workaround may be to create a service catalog item to create these additional resources (and create the item with "odo service create"), but I think it would be nice if odo was able to handle that natively without relying on a broker.

**Comment by mohammedzee1000** [comment]
Hey, thanks for raising an issue and recommending features. We are heading towards GA at the moment, so looking at new feature requests will likely only happen after that.
/heart
Thanks for understanding

**Comment by sspeiche** [comment]
@deweya how do you (or the customer) expect to create custom resources? I assume you are not talking about having something like `odo create -f mycf.yml` but something more like #2161.

What type of applications do they need to be able to create configmaps or secrets? Is it really just for items like `odo link` or other things not covered by `odo config`?

`odo` tries to simply some of the pieces of `kubectl/oc` so it would be good to understand what exactly what they are trying to do. Feel free to reach out to me directly.

2161

**Comment by kadel** [comment]
For ConfigMaps and Secrets we had an idea to implement something like this:

```
# create a new ConfigMap
odo config create myconfigmap --from-file config.cfg

# mount existing ConfigMaps  as a file to the component
odo config mount myconfigmap --path /etc/application/config.cfg

# or added it as an environment variable (using envFrom)
odo config add-env myconfigmap
```
The same flow for Secrets, only with additional flag `--secret`

It should be possible to share ConfigMaps and Secrets between multiple components, otherwise, one of their main benefits is lost. Users should be able to create one ConfigMap and add it to multiple components.

The only problem is that we have LocalConfig file `.odo/config.yaml` that should represent the whole component configuration and allow easily recreate the component with one command.
```
git clone my-awesome-repo
odo push
```
We need to figure out how we can capture ConfigMaps and Secrets in the LocalConfig and also allow sharing the same ConfigMaps and Secrets between multiple components.

**Comment by deweya** [comment]
@sspeiche I learned a bit more about the use case. I think for "custom resources", what they meant was the ability to declare other apps as dependencies.

For example, say you have a Spring Boot app with a MySQL db. Rather than deploying each separately (and join with `odo link`), they'd like the ability to declare the MySQL db a dependency of the Spring Boot app without having to explicitly `odo create` each component and then `odo link`.

Secrets and ConfigMaps are still a must. Essentially there's two issues here:
- Ability to create secrets and configmaps
- Ability to declare other apps as a dependency of another

If you guys also see it as two separate issues, I can split them up.

**Comment by sspeiche** [comment]
This feature is still valid

/lifecycle frozen

**Comment by kadel** [comment]
This has been implemented. 
Support for creating additional resources has been in odo since v2 release when odo started using devfile.yaml.

Starting with v3.6 odo supports pod-overrides and container-overrides which allows users to mount custom volumes, configmapes or secretes into the container defined in devfile.yaml

https://odo.dev/blog/odo-v3.6.0#extend-pod-and-container-specification-with-devfile-attributes-pod-overrides-and-container-overrides

/close
