### ISSUE TITLE
Add support for service catalog

### ISSUE THREAD

**Issue by containscafeine** [redhat-developer/odo#266]
We have service catalog search implemented in #243, but the current implementation of S2I does not support deploying templates from service catalog. Well, it should.

**Comment by kadel** [comment]
When `ocdev create` is called it should do series of checks like
 is componenttype s2i builder image? -> create new component using s2i builds
is componenttype service catalog "service" ->  instantiate new service using service catalog.

**Comment by containscafeine** [comment]
Mind dump -
1. get the kind of component type from `catalog.List()`, i.e. if it's an image stream or if it's a template
2. in either case, I should get a variable of type component, which implements an interface that looks like -
```golang
type componentCreate interface {
    CreateFromGit() error
    CreateFromBinary() error
    CreateFromLocal() error
}
```
3. call the relevant method on the component type

**Comment by kadel** [comment]
don't understand the interface part :-(

**Comment by surajnarwade** [comment]
@containscafeine , can you please elaborate on the interface part

**Comment by surajnarwade** [comment]
I explored `service catalog` a bit.

it works well, but there are some issues.

For example,

* User creates component,

```
odo create jenkins-ephemeral myjenkins
```

* odo calls service catalog api and deploy it as `serviceinstance`

* serviceinstace then creates deploymentconfig, service & routes as mentioned in templates.

* woo, we are good, not for so long.

* Now, User do,

```
odo list
```

* Nothing is there, because our deploymentconfig, services & routes don't have any labels.
(As of now, there is no any way to mention common labels in `ServiceInstace` of `Service catalog`)

Here's the proposal:

* user will write `odo create jenkins-ephemeral myjenkins`

* odo will call servicecatalog api and get that template. 

* then using template api from client-go, we will edit template and add labels to it.

* again using service catalog api, we will deploy the component as serviceinstance and so on.

Does this make sense ?

cc @containscafeine @kadel  @cdrage

**Comment by surajnarwade** [comment]
@kadel  @jorgemoralespou ,

```
Blockers:

* You can not label deploymentconfig, service, routes while creating serviceinstance

* You can not edit template from `openshift` namespace from a normal user

* By default, `template service broker` can only access template from `openshift` namespace (Reference: https://docs.openshift.org/latest/architecture/service_catalog/template_service_broker.html)



Proposed solution:

* copy template to current namespace, add required labels to it.

* Deploy using template client API instead of service catalog

```

**Comment by surajnarwade** [comment]
thanks @jwmatthews :)

**Comment by kadel** [comment]
We need to think about this a bit more.
Service Broker can create services outside of the cluster (for example AWD Service Broker).
We shouldn't really on the fact that there service created from service catalog is deployed to the cluster.

**Comment by kadel** [comment]
When I'm looking at the current implementation from the user's point of view, it could be confusing.
When you run `odo catalog list` you can seel all the component types (s2i images) and services.

The problem that there might be is that services are not really components (or they are really special kinds of components). It doesn't make sense to run `odo update`, `odo push` or `odo watch` on those. Another problem will be that services will require different kinds of parameters, and putting everything into one `odo create` command together with "regular" components might make that command too big and overloaded.

It might make sense to treat services from similarly to URLs and storage, and not as a type of the components.

Example:
```
# to create new service
odo service create mysql-persistent

# delete service
odo service delete mysql-persistent

# list existing/deployed services
odo service list
```

**Comment by surajnarwade** [comment]
@kadel , this makes sense
