### ISSUE TITLE
forwarding more than one port

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/odo#3495]
/kind feature

## Which functionality do you think we should add?
I would like to be able to forward more than one remote port using `odo debug port-forward`. Today this is not possible because I can set only a single remote host. I think there should be an option to provide local and remote port directly to the port-forward command  `odo debug port-forward LOCAL:REMOTE` without the config parameters. 

## Why is this needed?
To be able to use ports that are not normally exposed to public access, like traces, metrics etc.

**Comment by girishramnani** [comment]
@gorkem you can set the local port different everytime by using ` odo debug port-forward --local-port <port>`
You might not need to worry about remote port being same because each component has its own network space which wont conflict with other component.
But yes, this feature is definitely needed to configure the remote port if need be

**Comment by kadel** [comment]
> You might not need to worry about remote port being same because each component has its own network space which wont conflict with other component.

I think that @gorkem wants to have multiple port-forwards for the same component. Which is currently not possible because the remote ports is only controlled by env variable `DEBUG_PORT`

**Comment by girishramnani** [comment]
> > You might not need to worry about remote port being same because each component has its own network space which wont conflict with other component.
> 
> I think that @gorkem wants to have multiple port-forwards for the same component. Which is currently not possible because the remote ports is only controlled by env variable `DEBUG_PORT`

Do we have a usecase for that?

**Comment by gorkem** [comment]
I have needed it to forward a jupyter notebook kernel and debug it.

**Comment by kadel** [comment]
this is still valid

/remove-lifecycle rotten
/lifecycle frozen

>

**Comment by deboer-tim** [comment]
+1 to this. I think we should even discuss if HTTP port should be automatically forwarded, and at a minimum should be easier/less parameters to configure since we already know the port number.

Routes 'just work' on OpenShift, but installing ingress on Kind/Minikube and figuring out the host is non-trivial for the average user. Forwarding the HTTP port is much simpler for these users to get started.

**Comment by kadel** [comment]
with new `odo dev` implementation (#5425), every `endpoint` (expect those with `exposure: none`) will be automatically port-forwared to localhost
