### ISSUE TITLE
odo delete --wait doesn't wait for the resources to be terminated for devfile based components

### ISSUE THREAD

**Issue by girishramnani** [redhat-developer/odo#4593]
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

## How did you run odo exactly?
Created a nodejs component 
- added url
- added storage
- ran `odo delete -w -f`

## Actual behavior
odo delete exited immediately and I could see resources still in terminating state
```
NAME                   STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE 
storage-1-nmgsp-zdfk   Terminating   pvc-4379dd04-2f65-44c3-8166-83b324972df4   1Gi        RWO            gp2            65s 
storage-2-nmgsp-mphy   Terminating   pvc-46d37212-ce2b-4137-b923-c0ea513db929   1Gi        RWO            gp2            40s 
```

## Expected behavior
odo delete -w would wait for termination of resources

**Comment by kadel** [comment]
Test was commented out due to this in https://github.com/openshift/odo/pull/4518/files#diff-a66e004f045a81bb439831d545e16504af39186cce80fe777a29c6314f2bdbeeR666
After this is fixed the test should be uncommented.

**Comment by valaparthvi** [comment]
@kadel Which test?

**Comment by kadel** [comment]
> @kadel Which test?

`should delete the component and the owned resources with wait flag`
it is in tests/integration/component.go it will go in with https://github.com/openshift/odo/pull/4518

**Comment by kadel** [comment]
tests/integration/components.go 
`// It("should delete the component and the owned resources with wait flag", func() {`
it will go in with https://github.com/openshift/odo/pull/4518

**Comment by mohammedzee1000** [comment]
Based on my investigation, I have found that:

while the wait flag is respected for deletion during s2itun
https://github.com/openshift/odo/blob/1900fc15735fa6ac68e4a3b8ca456e2adea6b786/pkg/odo/cli/component/delete.go#L186

it is not respected anywhere at all for devfilerun

https://github.com/openshift/odo/blob/1900fc15735fa6ac68e4a3b8ca456e2adea6b786/pkg/odo/cli/component/delete.go#L225-L308

Based on my research, the wait flag should be passed when requesting deletion from cluster which happens below 

https://github.com/openshift/odo/blob/2c1cef43737b932fdf1b5ea0b85af3415e6b9435/pkg/odo/cli/component/devfile.go#L234

Which leads into below

https://github.com/openshift/odo/blob/2c1cef43737b932fdf1b5ea0b85af3415e6b9435/pkg/devfile/adapters/kubernetes/component/adapter.go#L579-L627

In essence, instead of doing DeleteDeployment, as below

https://github.com/openshift/odo/blob/2c1cef43737b932fdf1b5ea0b85af3415e6b9435/pkg/devfile/adapters/kubernetes/component/adapter.go#L619

`err = a.Client.GetKubeClient().Delete(labels, waitflagvalue)`

**Comment by mohammedzee1000** [comment]
Acceptance:

- [ ] Change Adapter Interface `Delete` function ot accept 3rd parameter, wait of type bool
- [ ] Apply respective updates to implementors (though only Kubernetes adapter will get to respect the wait value for now)
- [ ] Update Delete function in kubernetes adapter to use `err = a.Client.GetKubeClient().Delete(labels, waitflag)` instead of `DeleteDeployment`
- [ ] Add test(s) to ensure devfile component deletion respects wait flag

**Comment by feloy** [comment]
I'm re-opening this issue as the issue #4733 shows that in certain circumstances, some resources are not deleted before `odo delete --wait` terminates.

My understanding of [1] is that the dependent resources must have `ownerReference.blockOwnerDeletion=true` if we want odo to wait for the deletion of the dependent resource when deleting the parent with `propagationPolicy=Foreground`

Trying to set `ownerReference.blockOwnerDeletion=true` on OpenShift with the `developer` credentials on the dependent resources raises the error:

```
�[36mINFO�[0m[2021-05-25T10:32:39Z] [odo]  ✗  Failed to start component with name "openjdk-app".
Error: Failed to create the component: unable to create or update component: unable to create Service for openjdk-app:
services "openjdk-app" is forbidden:
cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil> 
```
Because of this, its seems not possible for `odo` to rely on the `Kubernetes API` and the `OwnerReferences` system to wait for the deletion of the dependent resource.

One way would be to wait for the deletion of these resources from `odo` itself.
 
[1] https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#foreground-cascading-deletion

**Comment by valaparthvi** [comment]
@feloy Is there any update on this issue?
I don't think this has been fixed: I checked by deleting a component with an attached service; the component got deleted, but odo did not wait for the resources related to the service to be deleted, they were still in terminating state when `odo delete` terminated.

**Comment by feloy** [comment]
Here is the current state: https://github.com/openshift/odo/issues/4733#issuecomment-847792991 

I didn't check since the last changes on the Push procedure.

**Comment by kadel** [comment]
We won't be fixing this in v2, and this doesn't apply for v3
