### ISSUE TITLE
Simplify user messages and reduce use of 'component'

### ISSUE THREAD

**Issue by deboer-tim** [redhat-developer/odo#4884]
/kind feature

## Which functionality do you think we should add?

The current error messages and prompts in commands like 'odo create' use the terms 'component' and 'devfile' a lot, and are not always in user-friendly terms. These messages add to the complexity and make it harder to use odo as a new user. The concept of a component is almost gone and we can rewrite these messages to be in simpler, user-focussed terms.

As an example here are some of the current messages and proposed alternatives, listed in pairs:

```
✗  The current directory does not represent an odo component. Use 'odo create' to create component here or switch to directory with a component
✗  The current directory has not been used with odo before. Use 'odo create' or switch to another directory.

Which devfile component type do you wish to create
Select the type of project (devfile) from the following list
or What type of project are you creating?

What do you wish to name the new devfile component
What is the name of this project?

What project do you want the devfile component to be created in
What project (namespace) do you want to publish to?
```

## Why is this needed?

New users don't know what a component or devfile is; non-OpenShift users don't know that a project is a namespace. Using simpler user-centric terms makes it easier to get started and reduces concept complexity.

**Comment by dharmit** [comment]
> These messages add to the complexity and make it harder to use odo as a new user. 

When I started with odo, `component` was the most difficult thing to get the grasp of. And it's still the number one pain for newcomers to odo.

> The concept of a component is almost gone and we can rewrite these messages to be in simpler, user-focussed terms.

I'm not sure what you mean by "concept of a component is almost gone". I mean, I am happy to hear that, but as far as odo is concerned, we are still _so_ tightly associated with "component"! `odo component` is a command that's invisible because everything's a component for odo. More like - component is the most basic unit of odo.

If we remove "component" from most places, what does `odo create` create for you, `odo push` push for you, `odo describe` describe for you, etc.? I'm all game about removing "component" word because it's difficult to explain it even in the documentation effort I'm doing right now.

As a user, "application" seems to be the right word to me, but we already have it [reserved for something else](https://github.com/redhat-developer/app-labels/blob/master/labels-annotation-for-openshift.adoc#terminology).

> ✗  The current directory does not represent an odo component. Use 'odo create' to create component here or switch to directory with a component
✗  The current directory has not been used with odo before. Use 'odo create' or switch to another directory.

I find this vague. Directory not used with odo _for what_/_to do what_? How's _just_ switching to another directory solve it if the other directory doesn't have a devfile just like `pwd` doesn't?
(Disclaimer: I'm only asking for us to think more on this; it's not just your task to answer this.)

>  Which devfile component type do you wish to create
Select the type of project (devfile) from the following list
or What type of project are you creating?

+1. But, again, how about calling it an "application" instead of project?

> What do you wish to name the new devfile component
What is the name of this project?

Again, how about "application"?

> What project do you want the devfile component to be created in
What project (namespace) do you want to publish to?

This makes sense.

----

@deboer-tim I get it that what you have mentioned here is just few examples.

My reasoning for using "application" in place of "component" is that, in my head, we are trying to help users run their applications on k8s/ocp. A 1-1 mapping there makes a lot of sense to me.

A project could be a group of applications - much like a label that helps list related items. This is what `odo app`/`application` in its current form does in odo. Or at least that's how I see it.

Namespace could be, well, a namespace. We discussed this in the past as well. Wouldn't it be safe to assume that someone with most basic knowledge of k8s knows of namespaces? OCP is a level above k8s, IMO.

**Comment by deboer-tim** [comment]
> > These messages add to the complexity and make it harder to use odo as a new user.
> 
> When I started with odo, `component` was the most difficult thing to get the grasp of. And it's still the number one pain for newcomers to odo.
> 
> > The concept of a component is almost gone and we can rewrite these messages to be in simpler, user-focussed terms.
> 
> I'm not sure what you mean by "concept of a component is almost gone". I mean, I am happy to hear that, but as far as odo is concerned, we are still _so_ tightly associated with "component"! `odo component` is a command that's invisible because everything's a component for odo. More like - component is the most basic unit of odo.

Internally, I agree odo components are still a thing. I was being a bit bold, but what I meant is as a concept for the end user: most people can use odo create, push, etc, only see the devfile on disk, and never really need to understand what an odo component is. Likewise I can clone a repo that contains a devfile and get odo push-ing right away.

> If we remove "component" from most places, what does `odo create` create for you, `odo push` push for you, `odo describe` describe for you, etc.? I'm all game about removing "component" word because it's difficult to explain it even in the documentation effort I'm doing right now. But if not "component" what do we call it?
> 
> As a user, "application" seems to be the right word to me, but we already have it [reserved for something else](https://github.com/redhat-developer/app-labels/blob/master/labels-annotation-for-openshift.adoc#terminology).

Agreed, this is one of the harder parts. Every term (component, application, project, ...) is already overloaded by IDEs, Kubernetes, etc. A few points:

- I don't want to simply swap 'component' for another term because that doesn't necessarily simplify anything, plus we'd have trouble explaining what 'odo component' does. :) My hope was to reduce or avoid the word where it's not really necessary, or find a term that is more natural/already used in others. If we have places where it really is an odo component we're referring to and you need to understand that, it's probably best to leave it as-is.
- In IDEs, a project is usually one git repo, which is usually one microservice, i.e. one odo component.
- In the OpenShift Dev Console, a project is a k8s namespace, which may contain multiple odo components/microservices. Application is increasingly used for a set of microservices that may span multiple namespaces, or are deployed to multiple environments/stages (dev, test, prod).
- In tools like Argo CD, ACM, application is also the higher-level construct that contains multiple microservices.
- Since 'application' is often used for this higher-level thing, I'd personally prefer to not use application in odo.

> > ✗  The current directory does not represent an odo component. Use 'odo create' to create component here or switch to directory with a component
> > ✗  The current directory has not been used with odo before. Use 'odo create' or switch to another directory.
> 
> I find this vague. Directory not used with odo _for what_/_to do what_? How's _just_ switching to another directory solve it if the other directory doesn't have a devfile just like `pwd` doesn't?
> (Disclaimer: I'm only asking for us to think more on this; it's not just your task to answer this.)

Agreed, this could be worded better. I think we should probably have a meeting to review these or spend a few tries on each one trying to find the most clear, concise, and consistent version. My main point in this case is that you shouldn't need to understand what 'representing a component' means - you just haven't used odo on this folder before and need to know about odo create.

> > Which devfile component type do you wish to create
> > Select the type of project (devfile) from the following list
> > or What type of project are you creating?
> 
> +1. But, again, how about calling it an "application" instead of project?

Ditto to comments above, I think 'application' is overloaded to be a set of projects/odo components.

> > What do you wish to name the new devfile component
> > What is the name of this project?
> 
> Again, how about "application"?

Ditto.

> > What project do you want the devfile component to be created in
> > What project (namespace) do you want to publish to?
> 
> This makes sense.
>
> @deboer-tim I get it that what you have mentioned here is just few examples.

Yes, there are many more messages we should review.

> My reasoning for using "application" in place of "component" is that, in my head, we are trying to help users run their applications on k8s/ocp. A 1-1 mapping there makes a lot of sense to me.
> 
> A project could be a group of applications - much like a label that helps list related items. This is what `odo app`/`application` in its current form does in odo. Or at least that's how I see it.
> 
> Namespace could be, well, a namespace. We discussed this in the past as well. Wouldn't it be safe to assume that someone with most basic knowledge of k8s knows of namespaces? OCP is a level above k8s, IMO.

Ditto to above, I think what people are typically using odo for is a part of a larger application. I would suggest using 'project' and inadvertently did in one of the suggestions above, but that's difficult because OpenShift (and odo) already use that for namespaces, which could contain multiple odo components.

This does re-enforce to me that my last suggestion was good though - we should include the term namespace when that's what we're referring to since it is more recognizable and easier for k8s users. I don't have a universally-better term for 'component' though, so maybe's it's best to remove any unnecessary use, improve references to other concepts like namespaces, and generally simplify messages, then discuss what's left.

**Comment by scottkurz** [comment]
> Ditto to above, I think what people are typically using odo for is a part of a larger application. I would suggest using 'project' and inadvertently did in one of the suggestions above, but that's difficult because OpenShift (and odo) already use that for namespaces, which could contain multiple odo components.

As alluded to, "project" is also used by [devfile](https://docs.devfile.io/devfile/2.1.0/user-guide/adding-projects-to-a-devfile.html).  If all odo is doing with this thing it calls "application" is setting and querying based on labels.. should the name reflect "label" somehow?    Or is there an idea to do more like somehow optimize the path through linking or even the outer loop build/deploy within this thing we're calling "application"?

> This does re-enforce to me that my last suggestion was good though - we should include the term namespace when that's what we're referring to since it is more recognizable and easier for k8s users

Agree, since odo is designed to manage generic k8s and OpenShift and 'project' is overloaded, maybe just use the more general "namespace".

> Internally, I agree odo components are still a thing. I was being a bit bold, but what I meant is as a concept for the end user: most people can use odo create, push, etc, only see the devfile on disk, and never really need to understand what an odo component is. Likewise I can clone a repo that contains a devfile and get odo push-ing right away.

And devfile components of course are a thing.    It'd be nice if there was only one level of 'component' to understand (devfile) when you got to that point (you shouldn't really need to think about it to push and run "Hello World").   But ...does an odo component map 1-1 to a container devfile component?  If so, maybe the user messages could be reworked to reflect that `odo create` is really about managing or deploying this devfile component to a target cluster than it is creating an odo-level component.  But is it really that simple?  I haven't really thought that through.

**Comment by deboer-tim** [comment]
I don't think there is an exact 1:1 mapping to devfile, but I would be cautious about exposing devfile terminology too - it would be good to be consistent, but for the same reasons above you shouldn't need to understand how devfiles work in order to use tools that are based on them.

From some side conversations I am more convinced that `application` will continue to be used for the bigger multi-container concept, and that `project` is the most overloaded term. I don't know if we could replace all current use of project with namespace, but we should at least qualify it.

**Comment by dharmit** [comment]
It seems to me that different projects use these terms to best fit their own story (I don't know if it's OK/not-OK to do so). I'll try to tabulate:


Term|devfile|IDEs|ODC|odo|
----|----|----|----|----|
`project`| A git project| A git project | A namespace | A namespace
`component`| [`container` or `kubernetes` or `openshift` or `volume`](https://docs.devfile.io/devfile/2.1.0/user-guide/api-reference.html)| N/A (same meaning as devfile?)| A microservice | A microservice
`application`/`app`|N/A|N/A|Set of microservices (label?)|Set of microservices (a.k.a label)
`namespace`| A k8s namespace| N/A (same as devfile?) | Aliased by `project` | Aliased by `project`

(`N/A` and question marks indicate that I don't know for sure.)

I think that we should try to have uniform terminology which stems from devfile because that's what all these tools have in common - they all rely on a devfile.

----
>>  I'm not sure what you mean by "concept of a component is almost gone". I mean, I am happy to hear that, but as far as odo is concerned, we are still so tightly associated with "component"! odo component is a command that's invisible because everything's a component for odo. More like - component is the most basic unit of odo.
>
> Internally, I agree odo components are still a thing. I was being a bit bold, but what I meant is as a concept for the end user: most people can use odo create, push, etc, only see the devfile on disk, and never really need to understand what an odo component is. Likewise I can clone a repo that contains a devfile and get odo push-ing right away.

But should they (odo components) really be a thing? We can get bold and remove the word "component" for good if it makes sense, no? Should we have the same meanings to things as devfile has? I mean, does it make sense to do so for odo? I didn't mean to argue in favour of continuing using the term "component" in odo in my previous comment.

However, if we want to keep the word "component" as-is, I think we could start using the term "microservice" more often along with it for users to understand things better.

> @deboer-tim: Since 'application' is often used for this higher-level thing, I'd personally prefer to not use application in odo.
> @scottkurz: If all odo is doing with this thing it calls "application" is setting and querying based on labels.. should the name reflect "label" somehow? Or is there an idea to do more like somehow optimize the path through linking or even the outer loop build/deploy within this thing we're calling "application"?

OK, makes sense to not use the term "application" for odo components.
I don't know if there's a plan to use "application" for something else in odo. @deboer-tim or @kadel could answer that.

> > Namespace could be, well, a namespace. We discussed this in the past as well. Wouldn't it be safe to assume that someone with most basic knowledge of k8s knows of namespaces? OCP is a level above k8s, IMO.
> 
> Ditto to above, I think what people are typically using odo for is a part of a larger application. I would suggest using 'project' and inadvertently did in one of the suggestions above, but that's difficult because OpenShift (and odo) already use that for namespaces, which could contain multiple odo components.

IMO, it makes sense to use "project" in place of "component" even though it means a namespace at the moment in odo. But I think there was an effort made to do this in the past, and we decided against it. Then why am I talking about it again? It's because we still find it difficult to explain what a "component" exactly means.

> This does re-enforce to me that my last suggestion was good though - we should include the term namespace when that's what we're referring to since it is more recognizable and easier for k8s users. I don't have a universally-better term for 'component' though, so maybe's it's best to remove any unnecessary use, improve references to other concepts like namespaces, and generally simplify messages, then discuss what's left.

Ah! It now seems to me that I took the conversation on this issue into a completely different direction than what you intended. Your intention is to only make "component" word appear less often than it does at various places. My bad. To address the original ask, I think we can:
1. Make it sound as comparable to a microservice
2. Reduce its references as much as possible in CLI and web docs.

> I don't think there is an exact 1:1 mapping to devfile, but I would be cautious about exposing devfile terminology too - it would be good to be consistent, but for the same reasons above you shouldn't need to understand how devfiles work in order to use tools that are based on them.

IMO, being consistent might help at development level and to the users (application architects?) who might want to work with devfiles. For odo, former is a valid scenario, latter isn't a concern. I am definitely not in the favour of exposing devfile and its terminology in CLI or web docs unless really, really required.

**Comment by scottkurz** [comment]
I guess another overloading is we also use 'component' to refer to "component type" when we do `odo catalog list components` to browse devfile registries... but I'm not sure that's really going to confuse anybody.   Just noting.

**Comment by dharmit** [comment]
This issue is about clearing the usage of word `component` from CLI messaging. Whether we should make similar change in https://odo.dev as well is something we will decide after making changes in CLI messaging.

**Comment by dharmit** [comment]
/triage needs-information

Need to figure out all the places in CLI messaging where we can remove `component` from.

**Comment by valaparthvi** [comment]
The most intuitive replacement I can think of for component is application, but as Tim suggested in his comment https://github.com/openshift/odo/issues/4884#issuecomment-876577245, it might not be the best idea to do that.
>Agreed, this is one of the harder parts. Every term (component, application, project, ...) is already overloaded by IDEs, Kubernetes, etc. A few points:
>
>    I don't want to simply swap 'component' for another term because that doesn't necessarily simplify anything, plus we'd have trouble explaining what 'odo component' does. :) My hope was to reduce or avoid the word where it's not really necessary, or find a term that is more natural/already used in others. If we have places where it really is an odo component we're referring to and you need to understand that, it's probably best to leave it as-is.
    In IDEs, a project is usually one git repo, which is usually one microservice, i.e. one odo component.
    In the OpenShift Dev Console, a project is a k8s namespace, which may contain multiple odo components/microservices. Application is increasingly used for a set of microservices that may span multiple namespaces, or are deployed to multiple environments/stages (dev, test, prod).
    In tools like Argo CD, ACM, application is also the higher-level construct that contains multiple microservices.
    Since 'application' is often used for this higher-level thing, I'd personally prefer to not use application in odo.

I'm finding it difficult to modify the messages in order to minimize the use of component and still make a sense out of the message.

Alternatively, we thought to completely replace the use of word 'component' with 'application' just for the messages, but then while reducing the user complexity, we might end up increasing the complexity and confusion for developers. We thought of using terms such as devworkspace(like devfile does) or microservice or devfile-component instead of component, but we could use an opinion on this. 

We are considering removing the command `odo component` since people hardly ever use it, we mostly just do `odo create` or `odo list` or `odo delete` and on and on and on.

Additionally, I think it is important to take into account what Dharmit said in his comment https://github.com/openshift/odo/issues/4884#issuecomment-878849794 about having a consistent naming scheme across all the projects.
>I think that we should try to have uniform terminology which stems from devfile because that's what all these tools have in common - they all rely on a devfile.

I also think this is important considering the direction in which we are going as a company. I understand that in the context of a project itself, it makes sense to use the terminology they're already using, but for the relatively new projects or projects like odo which are in early stage or have a lot of new changes coming in, we could use a common terminology.

**Comment by valaparthvi** [comment]
Is this issue still relevant? We seem to have ended up using 'component' again with v3, and our user messages are much better than before.

**Comment by valaparthvi** [comment]
I am going to close this after a discussion with Tomas. We have reduced the use of 'component' in our messages, and made them better. Feel free to reopen this issue if necessary.
