### ISSUE TITLE
Changes needed in docs.openshift.com related to odo push workflow.

### ISSUE THREAD

**Issue by kandarpamalipeddi** [redhat-developer/odo#4968]
/kind documentation

## What mistake did you find / what is missing in the documentation?
Observed old documentation found on [docs.openshift.com](https://docs.openshift.com/container-platform/4.7/cli_reference/developer_cli_odo/odo-architecture.html#odo-push-workflow_odo-architecture)

Openshift documentation should in sync with odo.dev.

**Comment by xkwangcn** [comment]
Documentation for ODO at [docs.openshift.com](https://docs.openshift.com/container-platform/4.7/cli_reference/developer_cli_odo/odo-architecture.html#odo-push-workflow_odo-architecture) is obsoleted and going to remove in further releases, so this issue can be closed now.

Then due to all the updated documents can be found at [odo.dev](https://odo.dev/), so workflow part also should be add in odo.dev, then created new issue #5090
