### ISSUE TITLE
odo displays state 'Locally Deleted' of a URL that is manually created on the cluster

### ISSUE THREAD

**Issue by valaparthvi** [redhat-developer/odo#4984]
/kind bug
## What versions of software are you using?

**Operating System:**
Fedora 34
**Output of `odo version`:**
odo v2.2.4 (87fc47703)
OpenShift Cluster: 4.8
## How did you run odo exactly?
1. Create a component
2. Push the component
3. Manually create a route on the OCP cluster.
4. Run `odo url list`.

## Actual behavior
The output of `odo url list` shows that the URL is 'Locally Deleted', when in face it was never created locally. And since it considers the URL deletion a local change, it suggests running `odo push`.
```sh
$ odo url list
Found the following URLs for component petclinic
NAME         STATE               URL                                                                                            PORT     SECURE     KIND
             Locally Deleted     http://www.petclinic-example-pvala.com                                                         0        false      route
8080-tcp     Pushed              http://8080-tcp-app-petclinic.apps.ci-ln-dt7idmb-f76d1.origin-ci-int-gce.dev.openshift.com     8080     false      route
There are local changes. Please run 'odo push'.
```
## Expected behavior
odo should be able to distinguish between Locally Created and Deleted, and Remotely Created URL.

## Any logs, error output, etc?

Note: I am yet to check this on a K8s/minikube cluster, but I don't see why this bug won't be reproducible there.

**Comment by kadel** [comment]
> odo should be able to distinguish between Locally Created and Deleted, and Remotely Created URL.

I think that this is makes sense. 

If there is an extra URL (Route or Ingress) odo should just ignore it.

**Comment by dharmit** [comment]
> > odo should be able to distinguish between Locally Created and Deleted, and Remotely Created URL.
> 
> I think that this is makes sense.
> 
> If there is an extra URL (Route or Ingress) odo should just ignore it.

I'm confused. Your response seems to agree to both mine & @valaparthvi's points, whereas our arguments are opposite. 

I'm suggesting that odo shouldn't care about ingress/route created outside the odo workflow; while @valaparthvi suggests odo should care. This is comparable to Operator backed services created using Web Console. `odo service list` would show them up at the moment and even let users link to such services.

So, then, why am I suggesting that odo shouldn't show such ingress/route in `odo url list`? It's because currently, such ingress/route gets deleted upon doing `odo push` as observed by @valaparthvi.

If odo is to support listing such ingress/route then, like `odo service delete`, odo needs to ensure that it doesn't delete a URL that wasn't created by it.

@mik-dass @valaparthvi @mohammedzee1000 correct me if I'm wrong in describing what we discussed on the call.

**Comment by feloy** [comment]
IMO, f the route created manually does not contain specific labels indicating it is managed by Odo, it should not be marked as `Locally Deleted`, but instead should either not be listed, or listed as somehting similar to `Created by another tool`

**Comment by kadel** [comment]
> I'm confused. Your response seems to agree to both mine & @valaparthvi's points, whereas our arguments are opposite.

What I wanted to describe was exactly the same idea as @feloy (https://github.com/openshift/odo/issues/4984#issuecomment-899352715)

Either completely hiding it or, marking it as "Created by other tool" and ignoring it from "push" logic are both valid solutions
