### ISSUE TITLE
Script for locally testing all devfile in a devfile registry.

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5114]
It would be great if we have a script that goes over all devfiles in a devfile registry and verifies that they can be used with odo. 

Test process
- list all devfiles in a given registry
- for each devfile
 - if it doesn't have a start project continue to next devfile in a list
 -  clone first starter project
 - place devfile into a directory where the starter project was cloned to
 - run `odo push`
 - check that each endpoint that is defined in devfile is responding

**Comment by dharmit** [comment]
My take is that we could try this after moving to IBM Cloud.

**Comment by kadel** [comment]
> My take is that we could try this after moving to IBM Cloud.

Why? There is nothing that would require IBM Cloud in this. 
The script should work locally against any cluster that you have configured in your KUBECONFIG There should be no dependency on IBM Cloud or any other provider.

**Comment by dharmit** [comment]
It's not about dependency on IBM Cloud. It's about prioritizing IBM Cloud and not adding more tests on top of an infra we're not planning to use long-term.

Why do I think that infra matters? It's because the two infras are not exactly alike. We have to make certain tweaks or configurations which are specific to one infra and then moving to IBM Cloud would render that effort useless.

What example do I have of the above comment? We used minikube with Docker driver in PSI, but IBM Kubernetes Service on IBM Cloud. Also, maybe, Ansible scripts we have written to bring up OCP 4.9 on IBM Cloud instead of relying prow to do it for us on AWS.

**Comment by kadel** [comment]
This issue is not about infra at all. The script that I have in mind would be executed on local machine against any cluster  that you are connected to. I'm not requesting adding this script to any of your CIs.

**Comment by dharmit** [comment]
Added it to the next Sprint's board. I missed the "local" part of the script from your previous comment. My bad.

**Comment by kadel** [comment]
/assign
I needed this for some of the changes that I have been doing on devfiles in registry, so I started implementing this.
I already have something that works, I just need to clean up before I open PR

**Comment by kadel** [comment]
The script is running as part of the devfile/registry CI https://github.com/devfile/registry/blob/main/tests/check_odov3.sh

/close
