### ISSUE TITLE
update quickstart to use `odo service create -p` instead of `--from-file`

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5212]
Quickstart guide uses yaml files to create postgresql sevice, instead it should use CLI only and use `-p` for `odo service create` 

/priority high
/kind documentation

**Comment by dharmit** [comment]
>  instead it should use CLI only

What's the rationale behind this? Genuinely trying to understand. Also, because the amount of parameters being set to create that service is probably large and hence it makes more sense to use `--from-file` than a long confusing and/or ugly looking `-p` flag.


> /priority high

Why? Again, genuinely trying to understand if this is causing troubles anywhere or to anyone.

**Comment by kadel** [comment]
> What's the rationale behind this? Genuinely trying to understand. Also, because the amount of parameters being set to create that service is probably large and hence it makes more sense to use `--from-file` than a long confusing and/or ugly looking `-p` flag.
> 
> >

odo goal is that you can do all basics from cli without resorting to modifing yaml fiels. Especially dealing with Operator CRs is quite pain. Users just want to crate database not to fight with writing big ass yaml files.

How would normal user know that they need to write yaml file for service and what the structure of the file should be?




> > /priority high
> 
> Why? Again, genuinely trying to understand if this is causing troubles anywhere or to anyone.

I agree that it doesn't have to be high, but I'm afraid that otherwise we will never address it :-/

**Comment by dharmit** [comment]
> odo goal is that you can do all basics from cli without resorting to modifing yaml fiels. Especially dealing with Operator CRs is quite pain. Users just want to crate database not to fight with writing big ass yaml files.
> 
> How would normal user know that they need to write yaml file for service and what the structure of the file should be?

But what about the cases where an Operator has too many fields in the spec that need to be set to create a usable service out of it. I am saying "usable" for a reason. We don't want to spin up an unusable service using only the required params.

What I'm trying to point here is that different Operators require different conditions/parameters to spin up a usable service. For some cases, the `--from-file` might actually be the "sensible" way (might not be the "right" way) to avoid writing a very long (or a long ass, as you rightly said) `odo service create -p` command.

My argument here is not specific to the quickstart guide. It's about Operators in general.
 
> > > /priority high
> > 
> > 
> > Why? Again, genuinely trying to understand if this is causing troubles anywhere or to anyone.
> 
> I agree that it doesn't have to be high, but I'm afraid that otherwise we will never address it :-/

It's maybe because majority issues opened on odo repo are high priority and so the team doesn't get opportunity to work on medium/low priority issues. But I could be wrong.

**Comment by kadel** [comment]
> What I'm trying to point here is that different Operators require different conditions/parameters to spin up a usable service. For some cases, the `--from-file` might actually be the "sensible" way (might not be the "right" way) to avoid writing a very long (or a long ass, as you rightly said) `odo service create -p` command.

Than the quick start guide needs to guide users how to create correct yaml file, or at least link to somewhere where user can lear how to do it. Just pointing to already created file without any additional explanation is not going to help anyone understand how  can they do something similar for their project.

**Comment by dharmit** [comment]
> Than the quick start guide needs to guide users how to create correct yaml file, or at least link to somewhere where user can lear how to do it.

I think quickstart guide should be to the point. Adding steps that talk about how to create yaml file like the one we are using would make the guide long, and deviate from explaining the main points.

However, we should cover this as a part of command reference for `odo service` command and that could be linked here.

> Just pointing to already created file without any additional  explanation is not going to help anyone understand how can they do something similar for their project.

We could point where the file used there comes from. Do you think command reference thing mentioned above would help with "help anyone understand how can they do something similar for their project." part of your concern?

**Comment by kadel** [comment]
> I think quickstart guide should be to the point. Adding steps that talk about how to create yaml file like the one we are using would make the guide long, and deviate from explaining the main points.

Problem is that currently it doesn't show how to create service, it just blindly applies some yaml file without trying to explain anything.  Quick start should help users to understand how to do basics with odo. This part fails to do that.
In this case we would be better off if we remove whole service part from quick start guide.
