### ISSUE TITLE
Dry run on Crunchy Postgresql fails

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5213]
```
$ odo service create postgresoperator.v5.0.3/PostgresCluster --dry-run   
 ✗  validation failure list:
.backups in body is required
```

**Comment by dharmit** [comment]
Does it fail with the main branch? I'm asking because we observed this in #5186 and fixed it in #5187.

**Comment by kadel** [comment]
> Does it fail with the main branch? I'm asking because we observed this in #5186 and fixed it in #5187.

yes, fails on current master f7c6299f0
```
▶ odo service create postgresoperator.v5.0.3/PostgresCluster --dry-run   
 ✗  validation failure list:
.backups in body is required

▶ odo version
odo v2.4.2 (f7c6299f0)
```

**Comment by feloy** [comment]
The problem also appears without the  `--dry-run`, and so we are not able to instantiate the example `PostgresCluster` with `odo`, because the example doe not respect the required fields.

Is it valid that odo fails, or should we add a `--no-validate` flag to instantiate the resource without validation?

**Comment by dharmit** [comment]
> The problem also appears without the `--dry-run`, and so we are not able to instantiate the example `PostgresCluster` with `odo`, because the example doe not respect the required fields.

I don't know why I missed this before opening the PR. While working on Quickstart guide, I faced this problem for the Crunchy Operator. As a result, I searched the Internet for a usable CRD to bring up Postgres and found what's now there in the quickstart repo.

The issue here is that we can't assume `alm-example` of the Operators to be a valid CRD. Some Operators might not even have the `alm-example` field at all, which would make `--dry-run` or `odo service create` without parameters or `--from-file` useless.

> Is it valid that odo fails, or should we add a `--no-validate` flag to instantiate the resource without validation?

`--no-validate` makes sense in such cases, IMO.

**Comment by kadel** [comment]
> The issue here is that we can't assume `alm-example` of the Operators to be a valid CRD. Some Operators might not even have the `alm-example` field at all, which would make `--dry-run` or `odo service create` without parameters or `--from-file` useless.

If we can't assume that `alm-examples` are valid, then we should not be using it as a default definition for `odo service create`.
It makes sense to use as a template for file. We will need to rething this

**Comment by dharmit** [comment]
> If we can't assume that `alm-examples` are valid, then we should not be using it as a default definition for `odo service create`. It makes sense to use as a template for file. We will need to rething this

You are not wrong, but there's no option other than `alm-examples`. At least I'm not aware of any.

On the cabal call we discussed this issue and had an idea that odo should still do the validation which led to the error message you reported. However, instead of reporting that error message, odo should tell the user that it can't spin up a usable service using the default parameters provided by the service, and that the user should manually pass parameters to create a service from this Operator.

WDYT?

**Comment by kadel** [comment]
> odo should tell the user that it can't spin up a usable service using the default parameters provided by the service

We are not using default parameters, but olm examples. Olm example != default values. As far as I know fields don't have default values. True default values need to be valid values.


I think that we will have to revisit how `odo service create` works.

For example something like this might be better than the current state:
```
$ odo service create postgresoperator.v5.0.3/PostgresCluster
You need to specify parameters in order to create PostgresCluster.
To get list of all available parameters run `odo catalog describe service  postgresoperator.v5.0.3/PostgresCluster`.
Or you can try creating PostgresCluster based on  Alm example using `--alm-example` flag.

$ odo service create postgresoperator.v5.0.3/PostgresCluster --dry-run
You need to specify parameters in order to create PostgresCluster.
To get list of all available parameters run `odo catalog describe service  postgresoperator.v5.0.3/PostgresCluster`
Or you can try creating PostgresCluster based on  Alm example using `--alm-example` flag.

```
Either `--alm-example` or `-p` flag will be required.

```
$ odo service create postgresoperator.v5.0.3/PostgresCluster --alm-example
 ✗  validation failure list:
.backups in body is required
```
This command fails with PostgresCluster, but it is ok. User is explicitly requesting use of alm examples. For other operators this might work.


```
$ odo service create postgresoperator.v5.0.3/PostgresCluster --alm-example --dry-run
 ✗  validation failure list:
.backups in body is required

# print out alm-example
```
This command will thread validation errors as warnings.





```
$ odo service create postgresoperator.v5.0.3/PostgresCluster -p field=value -p field1=value
# create service based on the parameters used
```

```
$ odo service create postgresoperator.v5.0.3/PostgresCluster -p field=value -p field1=value --dry-run
# just print out resource definition created based on the parameters
```

**Comment by kadel** [comment]
command no longer exists in v3

/close
