### ISSUE TITLE
Don't save component name in `env.yaml.

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5780]
The only thing that should control the name of the component is `metadata.name` in devfile.yaml.

Change the `metadata.name` and run `odo dev` again.

/kind bug
/priority high

**Comment by valaparthvi** [comment]
https://github.com/redhat-developer/odo/blob/d5935a16cc18f373037a3f127ceed4a21f173626/pkg/odo/cli/dev/dev.go#L145-L146

If it is of any help.

**Comment by dharmit** [comment]
From the comment https://github.com/redhat-developer/odo/issues/5862#issuecomment-1189057327:

> I think that #5780 is still valid. What we are currently doing (saving name in env.yaml) is not good, and it creates a lot of o problems. It still make sense to not save name and just use name from devfile.

@kadel can you explain what problems are we/users seeing because of storing the name in `env.yaml`? I looked at the issue description, but couldn't find any. I'm sure that something must have led you to open a high priority bug, but there's not enough information on this issue for a bug.

**Comment by dharmit** [comment]
Thanks for that explanation. Makes sense. 👍🏾
