### ISSUE TITLE
Ability to specify ServiceAccount for `odo dev`

### ISSUE THREAD

**Issue by vinny-sabatini** [redhat-developer/odo#5977]
/kind feature

## Which functionality do you think we should add?

When running the `odo dev` command, I would like to be able to specify the Kubernetes ServiceAccount the pod should run as.

## Why is this needed?

Currently, if you use `odo dev` the pod will start as the default service account. Some workloads running on Kubernetes need to run as a specific service account in order to have the proper permissions to work properly. One common use case is a Kubernetes Operator.

**Comment by dharmit** [comment]
Notes from the discussion on this in the odo contributors' call:
1. This should ideally be addressed at Devfile API level such that a `container` component has a `serviceAccount` attribute.
2. In absence of 1, odo can use `annotations` field in `container` component so that a service account specified in this field is used by odo to set proper information inside the Pod created for such component.

**Comment by rm3l** [comment]
To be done on the Devfile library side. See https://github.com/devfile/api/issues/920#issuecomment-1244059075

**Comment by rm3l** [comment]
TODO: Research if there is a library for JSON merge

**Comment by dharmit** [comment]
https://github.com/devfile/api/blob/fe7c10eaa530b12b19cfb0e22e221e753391304c/pkg/attributes/attributes.go#L14

**Comment by dharmit** [comment]
I've opened https://github.com/devfile/library/pull/155 for `container-overrides` part.

**Comment by rm3l** [comment]
**TODO** (as of Nov-23, 2022)
- [ ] Continue work on `container-overrides` PR above: https://github.com/devfile/library/pull/155
- [ ] PR for supporting `pod-overrides`

**Comment by valaparthvi** [comment]
This issue is slightly blocked on https://github.com/devfile/api/issues/1002.
We added the support for container-overrides and pod-overrides in devfile/library. But once we updated odo with the latest devfile/library, we discovered some issues related to https://github.com/devfile/api/issues/1002#issuecomment-1378302530. So for now, until the issue in question is fixed, we'll be slightly blocked.
I'm going to research some alternatives.
