### ISSUE TITLE
Reading environment variables from file

### ISSUE THREAD

**Issue by rludva** [redhat-developer/odo#5985]
/kind feature

## Which functionality do you think we should add?
Add a parameter for reading environment variables from a file, something like:
`$ odo env set --from-file /path/to/file-with-env-variables`

## Why is this needed?
When reading and setting many environment variables, it is important to process a lot of commands like `odo env set variable=value`, but if there is a project with about 50 or more variables, it is inconvenient to create an additional script with these commands.

**Comment by dharmit** [comment]
@rludva after discussing this with @kadel, we figured that it would be a better idea for this to be addressed at the devfile level so that various tooling created on top of it can benefit from it. I have opened an issue on the devfile repo, and will bring it up for discussion in the upcoming Devfile Community call that happens every Monday.

**Comment by dharmit** [comment]
@rludva do note that `odo env` command used to be a part of odo v2.x. That version of odo is in the maintenance mode, and the team is actively working on v3, which, as you can see from the [releases page](https://github.com/redhat-developer/odo/releases), is in beta phase.

Being able to add `--from-file` flag for odo v2 is out of the scope, but we could consider doing this for v3. That would also mean that you would have to switch to using v3 as and when it's doable on your side.
