### ISSUE TITLE
Enable contextual search in documentation

### ISSUE THREAD

**Issue by rm3l** [redhat-developer/odo#6198]
/area documentation
/kind user-story

## User Story
As a user, I want to see results that are relevant to the current version of the documentation I am reading, so that I am finding the right information I need.

This would fix the issue of having v2-related results when doing some search while reading the latest v3 documentation.

More details on https://docusaurus.io/docs/search#contextual-search

## Acceptance Criteria 
- [ ] Search on [odo.dev](https://odo.dev) should scope results to the current language and version

## Links 
- Related Epic (mandatory): &mdash;

/kind user-story

**Comment by dharmit** [comment]
> More details on https://docusaurus.io/docs/search#contextual-search

I had a feeling that this issue and https://github.com/redhat-developer/odo/issues/6194 are related because when I search the site for "binding", it doesn't show me anything from odo v3. But in the docusaurus docs, I read that contextual search is enabled by default. It's the first line in the aforementioned link.

For the case of #6194, I am going to mail the Aloglia support as mentioned in [this Slack thread](https://kubernetes.slack.com/archives/C01D6L2NUAG/p1665067356677979) and see if something's wrong with contextual search for odo website.

**Comment by rm3l** [comment]
Indeed, these two issues are related. Now that the search index has been refreshed via https://github.com/redhat-developer/odo/issues/6194, contextual search is working just fine on the website.

/close
