### ISSUE TITLE
Front end application are badly recognized with the NodeJS/Javascript devfile

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/odo#6210]
/kind bug

## What versions of software are you using?

**Operating System:**
Win10Pro

**Output of `odo version`:**
```
odo v3.0.0-rc2 (39a9a2874)                                 
                                                           
Server: https://api.sandbox.x8i5.p1.openshiftapps.com:6443 
Kubernetes: v1.23.5+012e945                                
```

## How did you run odo exactly?

odo analyze (on https://github.com/quarkusio/quarkus-super-heroes/tree/main/ui-super-heroes)

## Actual behavior

Report **NodeJS/Javascript** instead of **Angular/Typescript**

## Expected behavior

Should report **Angular/Typescript**

## Any logs, error output, etc?

alizer related (see https://github.com/redhat-developer/alizer/issues/105)

**Comment by rm3l** [comment]
/status blocked

Blocked on this issue on Alizer side: https://github.com/redhat-developer/alizer/issues/105

Once that is done, we'll need to update the Alizer library.

**Comment by rm3l** [comment]
Per the conversation in https://github.com/redhat-developer/alizer/issues/105, it looks like there is an issue in Alizer.

So marking this issue as blocked on https://github.com/redhat-developer/alizer/issues/114

**Comment by kadel** [comment]
after updating alizer (#6650)

it gets correctly detected as Quarkus 
```
▶ odo analyze -o json
[
	{
		"devfile": "java-quarkus",
		"devfileRegistry": "DefaultDevfileRegistry",
		"ports": [
			8085
		],
		"devfileVersion": "1.3.0"
	}
]
```

**Comment by rm3l** [comment]
> after updating alizer (#6650)
> 
> it gets correctly detected as Quarkus
> 
> ```
> ▶ odo analyze -o json
> [
> 	{
> 		"devfile": "java-quarkus",
> 		"devfileRegistry": "DefaultDevfileRegistry",
> 		"ports": [
> 			8085
> 		],
> 		"devfileVersion": "1.3.0"
> 	}
> ]
> ```

@kadel I think the issue was more about running `odo analyze` from [`ui-super-heroes`](https://github.com/quarkusio/quarkus-super-heroes/tree/main/ui-super-heroes), which is a sub-folder in `quarkus-super-heroes`.
With your changes in https://github.com/redhat-developer/odo/pull/6650, we are back to the original situation when this issue was reported: Alizer/`odo analyze` returns `nodejs` as the Devfile:

```json
[
  {
    "devfile": "nodejs",
    "devfileRegistry": "ns-devfile-registry",
    "devfileVersion": "2.1.1"
  }
]
```

But I think this issue is reporting that this is not really accurate, and Alizer/`odo analyze` should return `nodejs-angular` instead. And per the discussion in https://github.com/redhat-developer/alizer/issues/105#issuecomment-1346581126, the question was about detecting frameworks from the `devDependencies` list.
So I assume this is not really fixed yet if we want Alizer to detect frameworks from `devDependencies`.

**Comment by rm3l** [comment]
Since https://github.com/quarkusio/quarkus-super-heroes/pull/297, the UI Super-heroes app has become a Quarkus app, which is correctly detected by `odo analyze`:

```
$ odo analyze -o json
[
        {
                "devfile": "java-quarkus",
                "devfileRegistry": "StagingRegistry",
                "devfileVersion": "1.3.0",
                "name": "ui-super-heroes"
        }
]
```

Closing this issue for now due to inactivity, but feel free to reopen if needed.
Per https://github.com/redhat-developer/alizer/issues/105#issuecomment-1346581126, there is still the issue with making Alizer detect frameworks from `devDependencies` for projects with a `package.json` file. But this is an issue for Alizer.
