### ISSUE TITLE
odo create nodejs command not working as expected...

### ISSUE THREAD

**Issue by Dhruv-Soni11** [redhat-developer/odo#6312]
/kind bug

## What versions of software are you using?

**Operating System:** 
RHEL 8

**Output of `odo version`:

** odo v3.2.0 (233c817c5)

Server: https://api.crc.testing:6443
Kubernetes: v1.24.0+3882f8f

## How did you run odo exactly?
Followed steps from the following guide:

https://access.redhat.com/documentation/en-us/red_hat_openshift_local/2.5/html-single/getting_started_guide/index#deploying-sample-application-with-odo_gsg

## Actual behavior
Command throws an error

## Expected behavior
Successful creation of nodejs component

## Any logs, error output, etc?

```
Error: Subcommand not found, use one of the available commands: namespace
Usage:
  odo create [options] [flags]
  odo create [command]

Examples:
  # Create a new namespace and set it as the current active namespace
  odo create namespace my-namespace


Available Commands:
  namespace   Create a new namespace

Flags:
  -h, --help   Help for create

Additional Flags:
      --kubeconfig string    Paths to a kubeconfig. Only required if out-of-cluster.
  -o, --o string             Specify output format, supported format: json
      --run-on string        Specify target platform, supported platforms: "cluster" (default), "podman" (experimental)
  -v, --v Level              Number for the log level verbosity. Level varies from 0 to 9 (default 0).
      --var stringArray      Variable to override Devfile variable and variables in var-file
      --var-file string      File containing variables to override Devfile variables
      --vmodule moduleSpec   Comma-separated list of pattern=N settings for file-filtered logging

Use "odo create [command] --help" for more information about a command.

 ✗  Subcommand not found, use one of the available commands: namespace

```

Tagging @anjannath for additional reference.

**Comment by rm3l** [comment]
Hi @Dhruv-Soni11 !

Thanks for reporting this issue.

`odo create` is a v2-only command, which has been removed in v3 and replaced with [`odo init`](https://odo.dev/docs/command-reference/init).
The [guide you are referring to](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html-single/cli_tools/index#installing-odo) seems to make users install the `latest` version of `odo`, which at this time is v3.2.0

If you want to use `odo create` and proceed with the guide you are following, you need to [install v2](https://odo.dev/docs/2.5.0/getting-started/installation).
Otherwise, there is also an up-to-date QuickStart guide for Node.JS on [odo.dev](https://odo.dev/docs/user-guides/quickstart/nodejs)

**Comment by kadel** [comment]
I think that we can close this issue. 
This is going to be tracked on crc site as https://github.com/crc-org/crc/issues/3418

/close

**Comment by anjannath** [comment]
opened https://github.com/crc-org/crc/pull/3432 for this, would be nice get your views on the steps -- if a better/smoother workflow can be documented, thanks!
