### ISSUE TITLE
Odo panics when overriding parent:components:attributes:pod-overrides:spec:imagePullSecrets:name

### ISSUE THREAD

**Issue by AgentK9** [redhat-developer/odo#7099]
/kind bug

## What versions of software are you using?

**Operating System:** N/A (reproduced on windows and MacOS, but independent of OS or k8s back end)

**Output of `odo version`:** v3.14.0

## How did you run odo exactly? 

`brew install odo`, `odo dev`.

This may be an issue with the devfile library, unsure.

## Actual behavior

See [here](https://gist.github.com/AgentK9/919988b620dde8f044ca411a3779c1e5) for error message

## Expected behavior

No error. `odo dev` runs as expected 

## Any logs, error output, etc?

See POC repo [here](https://github.com/AgentK9/devfile-override-bug)

**Comment by rm3l** [comment]
Hi @AgentK9!

Thanks for reporting the issue and providing a sample repro repo.
FYI, the attribute for overriding properties of the pod spec is [`pod-overrides`](https://devfile.io/docs/2.2.0/overriding-pod-and-container-attributes#pod-overrides), not `pod-override`. Anyway, even with that, the issue was still there.
From the stacktrace, it looks like an issue with how the Devfile library merges complex attributes when handling a parent-child relationship.
I'll report this to the Devfile library repo, and when it is fixed there, we'll need to update `odo` accordingly.

/status blocked

**Comment by AgentK9** [comment]
Awesome! Thanks for the quick response. Edited the title to reflect your comment. Hope this gets resolved soon!

**Comment by rm3l** [comment]
> Still an issue!

Reopening, but still blocked by https://github.com/devfile/api/issues/1268

/reopen
/remove-lifecycle stale
/remove-lifecycle rotten
