### ISSUE TITLE
Deprecation Notice for Service Binding Operator

### ISSUE THREAD

**Issue by jeffgus** [redhat-developer/odo#7254]
/kind bug

The `odo add binding` command requires the Service Binding Operator, but the page shows that the operator has been deprecated as of Feb 2024.

## What versions of software are you using?

**Operating System:**
Fedora 40

**Output of `odo version`:**
odo v3.16.1 (cd346c5e6-nightly)

Server: https://xxxxxxxxxxxxxxxxxx:6443
OpenShift: 4.14.27
Kubernetes: v1.27.13+048520e
Podman Client: 5.1.1

## How did you run odo exactly?
`odo add binding`

## Actual behavior
✗  Service Binding Operator is not installed on the cluster, please ensure it is installed before proceeding. See installation instructions: https://odo.dev/docs/command-reference/add-binding#installing-the-service-binding-operator

## Expected behavior
I can install the operator, but should I since it is now deprecated?

**Comment by jeffgus** [comment]
I installed https://github.com/servicebinding/runtime which appears to be the replacement for the operator, but `odo` doesn't recognize it.

**Comment by rm3l** [comment]
@jeffgus Thanks for the info about the deprecation notice! I've added this as a warning to all the doc pages mentioning the Service Binding Operator, like https://odo.dev/docs/command-reference/add-binding
Unfortunately, there is currently no plan to support https://github.com/servicebinding/runtime as a replacement.

Alternatively, it should be possible to connect to other services without the Service Binding Operator. See this blog post for a detailed walkthrough: https://odo.dev/blog/binding-database-service-without-sbo

Closing this issue as done (by mentioning the deprecation notice in the odo docs), but feel free to reopen if you think otherwise.

/close
