### ISSUE TITLE
Improve Delete command

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#804]
- Delete should show what other things get deleted as part the action
  - If cascading delete includes storage, should again ask for removal confirmation

**Comment by kadel** [comment]
This should be done after the new structure of the command is defined by https://github.com/redhat-developer/odo/issues/785

**Comment by kadel** [comment]
review: @cdrage @syamgk

**Comment by anmolbabu** [comment]
@kadel So this is a first time confirmation before triggering delete right? Not like I choose to delete everything else other than say storage for example? So I delete everything or nothing?

**Comment by anmolbabu** [comment]
Based on my conversation with @kadel , this issue is about:
1. Detecting everything that's part of what is being deleted
2. Additional to the delete confirmation message say what all resources are part of the resource being deleted as part of the confirmation
3. Based on user input delete everything that's part(associated with) of resource being deleted or delete nothing

**Comment by kadel** [comment]
One note for implementation:
Kubernetes has [garbage collection](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/). If you make sure that resources have correct `ownerReferences` it will make cascading deletion easier. 
For exaple if you set `ownerReferences` on the Route that points to a DeploymentConfig. Than once you delete the DeploymentConfig, Kubernetes will automaticaly delete associated Route.

**Comment by mohammedzee1000** [comment]
I guess this can happen at different levels:
deletes of project -> deletes apps -> which deleted components/services -> deletes attached storage / routes

Are `ownerReferences` currently being set. If not i guess that would be first step to ensure all objects are getting them. 

Assuming they are set, we also need to be able to pick up objects from lower level(s) with appropriate references so that we can list them (and assuming they are set) and then initiate deletion.

This does bring up one question, in case of storage, the second confirmation should either happen with first confirmation or we cannot use `ownerReferences` with storage as initiation of deletion will automatically cause deletion of all objects down the chain

@kadel @anmolbabu

**Comment by mohammedzee1000** [comment]
Application already lists components that will be affected, but URLs are not listed, updating code to list URLs as well

**Comment by mohammedzee1000** [comment]
Component now lists affected children
```
$ odo component delete nodejs-ex-nodejs-npik
 URL  nodejs-ex-nodejs-npik-8080 ,  nodejs-ex-nodejs-npik-8080-nodejs-ex-qxcx-myproject.192.168.42.70.nip.io will be removed
Are you sure you want to delete nodejs-ex-nodejs-npik from nodejs-ex-qxcx? [y/N]: n
Aborting deletion of component: nodejs-ex-nodejs-npik

```

**Comment by kadel** [comment]
It might be good to format it a little bit to make it easier to read.

Maybe something like this:


```
$ odo component delete nodejs-ex-nodejs-npik
The component has following urls that will be deleted with component:
   -  nodejs-ex-nodejs-npik-8080-nodejs-ex-qxcx-myproject.192.168.42.70.nip.io will 

Are you sure you want to delete nodejs-ex-nodejs-npik from nodejs-ex-qxcx? [y/N]: n
Aborting deletion of component: nodejs-ex-nodejs-npik
```

**Comment by mohammedzee1000** [comment]
Improved messaging:

```
$  odo project delete myproject
This project contains the following applications, which will be deleted

 Application  nodejs-ex-irze

  This application has following components that will be deleted

  component named  nodejs-ex-nodejs-fsfx

    The component has following urls that will be deleted with component

     URL named  nodejs-ex-nodejs-fsfx-8080  with value  nodejs-ex-nodejs-fsfx-8080-nodejs-ex-irze-myproject.192.168.42.216.nip.io

Are you sure you want to delete project myproject? [y/N]: n
 ✗  Aborting deletion of project: myproject

$ odo application delete nodejs-ex-irze
This application has following components that will be deleted

 component named  nodejs-ex-nodejs-fsfx

  The component has following urls that will be deleted with component

   URL named  nodejs-ex-nodejs-fsfx-8080  with value  nodejs-ex-nodejs-fsfx-8080-nodejs-ex-irze-myproject.192.168.42.216.nip.io

Are you sure you want to delete the application: nodejs-ex-irze from project: myproject? [y/N]: n
 ✗  Aborting deletion of application: nodejs-ex-irze

$ odo component delete nodejs-ex-nodejs-fsfx
The component has following urls that will be deleted with component

 URL named  nodejs-ex-nodejs-fsfx-8080  with value  nodejs-ex-nodejs-fsfx-8080-nodejs-ex-irze-myproject.192.168.42.216.nip.io

Are you sure you want to delete nodejs-ex-nodejs-fsfx from nodejs-ex-irze? [y/N]: n
 ✗  Aborting deletion of component: nodejs-ex-nodejs-fsfx


```
