### ISSUE TITLE
STDERR output is not showing in logs

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#840]
[kind/bug]

## How did you run odo exactly?
having simple python app
```python
# app.py
import sys

sys.stderr.write("STDERR\n")
sys.stdout.write("STDOUT\n")
```

```
odo create python
odo push
odo log
```

## Expected behavior
see both `STDOUT` and `STDERR` outputs

## Actual behavior

I can see only `STDOUT`

`odo log`

```
Setting up
Running
---> Running application from Python script (app.py) ...
STDOUT
time="2018-10-17T11:57:36Z" level=debug msg="wait program exit" program=run
time="2018-10-17T11:57:36Z" level=info msg="program stopped with status:exit status 0" program=run
time="2018-10-17T11:57:36Z" level=info msg="Don't start the stopped program because its autorestart flag is false" program=run
```

This is big problem, because you won't even see if you have invalid syntax in your code :-(

**Comment by kadel** [comment]
review: @geoand @mik-dass

**Comment by syamgk** [comment]
I take a look at this and noticed that we did have stderr coming on logs in `odo version v0.0.12`

if we can add 
```
stderr_logfile=/dev/stdout
stderr_events_enabled=true
```
to the below config file then the stderr will also be coming along with the other logs
https://github.com/redhat-developer/odo-supervisord-image/blob/master/supervisor.conf

Its easy to test this since the config file resides in the persistent storage, 
Just edit the config after execing into the pod and add those lines and kill process 1/restart the pod 
the next time the pod comes up with the patched configuration 
But I'm not sure if this is the right approach, @kadel @cdrage please comment

**Comment by syamgk** [comment]
also raised a PR here https://github.com/redhat-developer/odo-supervisord-image/pull/2

**Comment by cdrage** [comment]
@syamgk The PR raised looks good to me, seems like that'd fix the issue :+1:

**Comment by geoand** [comment]
Makes sense to me as well @syamgk

**Comment by surajnarwade** [comment]
Closing since https://github.com/redhat-developer/odo-supervisord-image/pull/2 and  #901 is merged now :tada:
