### ISSUE TITLE
Available build for every PR

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#890]
Every PR should binaries so anyone can try and test PRs without needing to build it yourself.

I've tried it here https://github.com/redhat-developer/odo/pull/833
But failed because of Travis-ci security limitations.

**Comment by jorgemoralespou** [comment]
@LalatenduMohanty @praveenkumar can you help @kadel or anyone on this project to set this up? You have it working

**Comment by syamgk** [comment]
spoke to lala
they have build artifacts published on appveyor and centos CI
I think appveyor is good enough for us since we can cross compile for three architectures.

eg from minishift build: https://ci.appveyor.com/project/budhrg/minishift/builds/19821615/artifacts

I'm proceeding with configuring appveyor for odo

**Comment by syamgk** [comment]
closing since all the tasks associated with it are finished and its live now
